/** Tailwind preset — maps the reference tokens to utility classes. */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        status: 'var(--status)',
        trend: 'var(--trend)',
        'trend-muted': 'var(--trend-muted)',
        track: 'var(--track)',
        sidebar: 'var(--sidebar)',
        'sidebar-foreground': 'var(--sidebar-foreground)',
        'sidebar-border': 'var(--sidebar-border)',
        'line-strong': 'var(--line-strong)',
        subtle: 'var(--subtle)',
        faint: 'var(--faint)',
        soft: 'var(--soft)',
        chip: 'var(--chip)',
        icon: 'var(--icon)',
        'check-fill': 'var(--check-fill)',
        'tag-blue': { bg: 'var(--tag-blue-bg)', border: 'var(--tag-blue-border)', fg: 'var(--tag-blue-text)' },
        'tag-purple': { bg: 'var(--tag-purple-bg)', border: 'var(--tag-purple-border)', fg: 'var(--tag-purple-text)' },
        'tag-green': { bg: 'var(--tag-green-bg)', border: 'var(--tag-green-border)', fg: 'var(--tag-green-text)' },
        'tag-moss': { bg: 'var(--tag-moss-bg)', border: 'var(--tag-moss-border)', fg: 'var(--tag-moss-text)' },
        'tag-red': { bg: 'var(--tag-red-bg)', border: 'var(--tag-red-border)', fg: 'var(--tag-red-text)' },
        'tag-orange': { bg: 'var(--tag-orange-bg)', border: 'var(--tag-orange-border)', fg: 'var(--tag-orange-text)' },
        'tag-amber': { bg: 'var(--tag-amber-bg)', border: 'var(--tag-amber-border)', fg: 'var(--tag-amber-text)' },
        'tag-teal': { bg: 'var(--tag-teal-bg)', border: 'var(--tag-teal-border)', fg: 'var(--tag-teal-text)' },
        'tag-yellow': { bg: 'var(--tag-yellow-bg)', border: 'var(--tag-yellow-border)', fg: 'var(--tag-yellow-text)' },
        'tag-neutral': { bg: 'var(--tag-neutral-bg)', border: 'var(--tag-neutral-border)', fg: 'var(--tag-neutral-text)' },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        xl: 'calc(var(--radius) + 4px)',
      },
      boxShadow: {
        raised: 'var(--shadow-raised)',
        primary: 'var(--shadow-primary)',
        chip: 'var(--shadow-chip)',
        overlay: 'var(--shadow-overlay)',
      },
      transitionTimingFunction: {
        'power3-out': 'var(--ease-power3-out)',
      },
    },
  },
};